name: Node CI

on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Frontend App"
  
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Backend App"