name: Node CI

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18,20,22]
  
    steps:
      - run: echo ${{ matrix.node-version }}      


